name: CI

on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 19.2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10.8'

      - name: Cache yarn
        uses: actions/cache@v1
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: pip install
        run: pip install -r requirements.txt

      - name: Pytest
        env:
          AWS_DEFAULT_REGION: us-east-1
        run: source ./.env.testing.sample && pytest -ra -v --durations=10

      - name: Run yarn install
        run: yarn install --frozen-lockfile

      # - name: sls package
      #   env:
      #     AWS_DEFAULT_REGION: us-east-1
      #     AWS_ACCESS_KEY_ID: XXXXXXXXXXXXXXXXXXXX
      #     AWS_SECRET_ACCESS_KEY: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      #   run: cp ./secrets/sample.json ./secrets/local.json && sls package --stage local
